version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8088:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?client_encoding=utf8
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  postgres_data:
