"""Add start_date to Card and color to Board

Revision ID: 8decc0c3b948
Revises: 226ad83ccd8b
Create Date: 2025-09-23 19:56:36.622709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8decc0c3b948'
down_revision: Union[str, Sequence[str], None] = '226ad83ccd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('color', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cards_start_date'), 'cards', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_start_date'), table_name='cards')
    op.drop_column('cards', 'start_date')
    op.drop_column('boards', 'color')
    # ### end Alembic commands ###
