"""add due_date to cards

Revision ID: acf35b063731
Revises: c07bd0e91a8e
Create Date: 2025-09-23 08:23:41.848347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf35b063731'
down_revision: Union[str, Sequence[str], None] = 'c07bd0e91a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cards_due_date'), 'cards', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_due_date'), table_name='cards')
    op.drop_column('cards', 'due_date')
    # ### end Alembic commands ###
